FROM apache/airflow:2.10.5-python3.12

USER root

RUN groupadd airflow && usermod -aG airflow airflow

USER airflow
COPY pyproject.toml /home/airflow/
RUN pip install /home/airflow/
USER root

COPY . /home/airflow/mlops_project
RUN chown -R airflow:airflow /home/airflow/mlops_project

USER airflow

WORKDIR /home/airflow/mlops_project

RUN pip install .
RUN dvc init --no-scm