train:
  learning_rate: 0.001
  hidden_layer_1_neurons: 64
  hidden_layer_2_neurons: 32
  dropout_rate: 0.3
  epochs: 100
  batch_size: 32
  random_seed: 42

preprocess_data:
  test_size: 0.2
  random_seed: 42
